# Generated by Django 6.1 on 2026-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='closing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='opening_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
