# Generated by Django 6.1 on 2026-09-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_closing_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagedstock',
            name='reported_by',
            field=models.CharField(blank=True, default='Store Manager', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalstockverification',
            name='verified_by',
            field=models.CharField(blank=True, default='System Inspector', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transferred_by',
            field=models.CharField(blank=True, default='System Operator', max_length=100, null=True),
        ),
    ]
