# Generated by Django 6.1 on 2026-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('minimum_stock_level', models.IntegerField(default=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
