"""
app/auth/models.py

SQLAlchemy ORM models for authentication, device management, and session lifecycle.

Design decisions (ADR-001):
  - Device represents a unique client installation environment, NOT physical hardware.
    The client generates `device_identifier` and persists it in platform-appropriate
    secure storage. The server never generates this value.
  - Exactly one active Session may exist per Device at any time (one-session-per-device).
  - SHA-256(jti) is stored for refresh tokens; plaintext is never persisted.
  - All revocations set `revoked_at` and `logout_reason` for security analytics.
"""

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.base import Base, new_uuid


class Credential(Base):
    """
    Separate credential record so a user could later have multiple
    credential types (password, OAuth, passkey) without touching the User table.

    Note: password_updated_at lives on User (not here) so that the JWT
    middleware can check it in a single JOIN with the session query, rather
    than requiring an extra round-trip to this table.
    """

    __tablename__ = "credentials"

    id = Column(String, primary_key=True, default=new_uuid)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )
    password_hash = Column(String, nullable=False)

    # Relationship
    user = relationship("User", back_populates="credential")


class Device(Base):
    """
    A Device represents a unique client installation environment,
    NOT physical hardware.  A user running Chrome and the desktop app
    on the same laptop produces two separate Device records â€” each has
    its own storage sandbox, lifecycle, and revocation boundary.

    device_identifier is a stable UUID generated by the client and persisted
    in platform-appropriate secure storage (localStorage / Keychain /
    EncryptedSharedPreferences / AppData).  The server never generates this â€”
    the client owns it.
    """

    __tablename__ = "devices"

    id = Column(String, primary_key=True, default=new_uuid)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Stable client-generated UUID.  Unique per (user, device_identifier).
    device_identifier = Column(String, nullable=False)

    # Platform of the client installation.
    # Values: web | android | ios | windows | macos | linux
    platform = Column(String(20), nullable=False, default="web")

    # System-level device label provided by the client OS
    # (e.g. "iPhone 15 Pro", "DESKTOP-ABC123").
    device_name = Column(String(255), nullable=False, default="Unknown")

    # User-editable human label (e.g. "My Work Laptop").
    friendly_name = Column(String(255), nullable=True)

    # Derived by the backend from the User-Agent header.
    # Null for native apps that don't use a browser UA string.
    browser = Column(String(100), nullable=True)
    operating_system = Column(String(100), nullable=True)

    # Provided by native clients (mobile/desktop). Null for web.
    app_version = Column(String(50), nullable=True)

    # Current User-Agent string â€” overwritten on each login.
    # The Session model stores an immutable UA snapshot for audit purposes.
    user_agent = Column(Text, nullable=True)

    # FCM (Android) or APNs (iOS) push notification token.
    push_token = Column(Text, nullable=True)

    # User-controlled trust flag. Trusted devices may bypass additional
    # verification steps in future MFA flows.
    trusted = Column(Boolean, default=False, nullable=False)

    # Soft deactivation flag. A deactivated device cascades revocation
    # to all its active sessions but retains audit history.
    is_active = Column(Boolean, default=True, nullable=False)

    first_seen_at = Column(DateTime(timezone=True), server_default=func.now())
    last_seen_at = Column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        # Enforce the one-device-per-identifier-per-user constraint.
        UniqueConstraint("user_id", "device_identifier", name="uq_user_device_identifier"),
        # Common query: all active devices for a user.
        Index("ix_devices_user_id_is_active", "user_id", "is_active"),
    )

    # Relationships
    user = relationship("User", back_populates="devices")
    sessions = relationship("Session", back_populates="device", cascade="all, delete-orphan")
    login_histories = relationship("LoginHistory", back_populates="device")


class Session(Base):
    """
    A Session represents one active authenticated login.
    Exactly one active Session may exist per Device at any time.
    Logging in from a Device always revokes any prior active Session
    for that same Device before creating a new one.
    """

    # Enumerated logout reasons required for security analytics and
    # incident investigation. Without these it is impossible to
    # distinguish voluntary logout from a rotation breach revocation.
    LOGOUT_REASONS = [
        "user_logout",        # User-initiated logout
        "logout_all",         # User logged out all sessions
        "password_reset",     # Password reset invalidated all sessions
        "session_replaced",   # New login on same device replaced this session
        "device_deactivated", # Device was deactivated
        "limit_enforced",     # Global session limit enforcement
        "rotation_breach",    # Refresh token rotation breach detected
        "admin_revoked",      # Revoked by an administrator
    ]

    __tablename__ = "sessions"

    id = Column(String, primary_key=True, default=new_uuid)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    device_id = Column(
        String,
        # CASCADE: if the device is hard-deleted, the session is meaningless.
        ForeignKey("devices.id", ondelete="CASCADE"),
        nullable=False,
    )

    # SHA-256 hash of the refresh token's jti claim.
    # Plaintext is never persisted. Max 64 chars = exact SHA-256 hex digest length.
    refresh_token_hash = Column(String(64), unique=True, nullable=True, index=True)

    # Network audit fields captured at login time. Immutable after creation.
    ip_address = Column(String(45), nullable=True)  # 45 chars fits IPv6

    # Immutable point-in-time UA snapshot for this login.
    # Device.user_agent is mutable (overwritten on each login);
    # Session.user_agent is a permanent audit record.
    user_agent = Column(Text, nullable=True)

    # NOT server_default â€” only updated on token refresh, not on revocation.
    # Using server_default would overwrite this on every .save() including revocations.
    last_activity_at = Column(DateTime(timezone=True), nullable=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    revoked = Column(Boolean, default=False, nullable=False)

    # Populated when revoked=True. Enables "when did session X end?" queries
    # which are required for security audit trails.
    revoked_at = Column(DateTime(timezone=True), nullable=True)

    # Required for security analytics. Distinguishes voluntary logout from
    # breach-triggered revocation, session replacement, etc.
    logout_reason = Column(String(50), nullable=True)   

    __table_args__ = (
        # Most common query pattern: active sessions for a user.
        Index("ix_sessions_user_id_revoked", "user_id", "revoked"),
        # Device deactivation cascade: sessions for a device.
        Index("ix_sessions_device_id_revoked", "device_id", "revoked"),
        # Cleanup job query: expired sessions.
        Index("ix_sessions_expires_at_revoked", "expires_at", "revoked"),
    )

    # Relationships
    user = relationship("User", back_populates="sessions")
    device = relationship("Device", back_populates="sessions")
    login_histories = relationship("LoginHistory", back_populates="session")


class LoginHistory(Base):
    """
    Append-only audit log of all login attempts (successful and failed).
    Foreign keys use SET_NULL so history is preserved when related
    records are deleted.
    """

    __tablename__ = "login_history"

    id = Column(String, primary_key=True, default=new_uuid)

    # Nullable: failed logins for non-existent users have no user FK.
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True,
    )
    session_id = Column(
        String,
        ForeignKey("sessions.id", ondelete="SET NULL"),
        nullable=True,
    )
    # Direct device FK enables "all login attempts for this device" queries
    # without needing to join through Sessions.
    device_id = Column(
        String,
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
    )

    success = Column(Boolean, nullable=False)
    ip_address = Column(String(45), nullable=True)
    user_agent = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        # Efficient "login history for a user in time order" queries.
        Index("ix_login_history_user_id_created_at", "user_id", "created_at"),
    )

    # Relationships
    user = relationship("User", back_populates="login_histories")
    session = relationship("Session", back_populates="login_histories")
    device = relationship("Device", back_populates="login_histories")


class EmailVerificationToken(Base):
    __tablename__ = "email_verification_tokens"

    id = Column(String, primary_key=True, default=new_uuid)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # SHA-256 hash of the raw token. Plaintext never stored.
    token_hash = Column(String(64), unique=True, nullable=False, index=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    used = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="email_verification_tokens")


class PasswordResetToken(Base):
    __tablename__ = "password_reset_tokens"

    id = Column(String, primary_key=True, default=new_uuid)
    user_id = Column(
        String,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # SHA-256 hash of the raw token. Plaintext never stored.
    token_hash = Column(String(64), unique=True, nullable=False, index=True)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    used = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="password_reset_tokens")
