import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Monitor, Smartphone, Tablet, LogOut } from "lucide-react";
import api from "../../services/api";
import AuthNavbar from "../../components/authentication/shared/AuthNavbar";
import AuthFooter from "../../components/authentication/shared/AuthFooter";

const iconFor = (platform = "") => /android|ios|mobile/i.test(platform) ? Smartphone : /tablet|ipad/i.test(platform) ? Tablet : Monitor;
const label = (v) => v || "Unknown";
export default function SessionManagement() {
  const [sessions,setSessions]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const navigate=useNavigate();
  const load=()=>{setLoading(true); api.get("/auth/sessions").then(({data})=>setSessions(Array.isArray(data)?data:[])).catch(e=>setError(e?.response?.data?.detail||"Unable to load sessions.")).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const revoke=async(id)=>{try{await api.delete(`/auth/sessions/${id}`);load();}catch(e){setError(e?.response?.data?.detail||"Unable to revoke session.");}};
  const revokeAll=async()=>{try{await api.post("/auth/logout-all");load();}catch(e){setError(e?.response?.data?.detail||"Unable to revoke sessions.");}};
  return <div className="min-h-screen flex flex-col bg-[#f8f9ff]"><AuthNavbar/><main className="flex-1 px-4 md:px-8 py-8 max-w-[1200px] mx-auto w-full"><div className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-semibold text-[#121c2a]">Session Management</h1><p className="text-sm text-[#424751]">Only sessions returned by the authenticated ERP API are shown.</p></div><button onClick={revokeAll} className="rounded-lg bg-[#004287] px-5 py-2.5 text-sm font-semibold text-white">Revoke All Other Sessions</button></div>{error&&<div className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-xl border border-[#c2c6d3] bg-white"><div className="border-b p-4 font-semibold">Active Sessions ({sessions.length})</div>{loading?<div className="p-8 text-center text-sm text-[#737782]">Loading sessions…</div>:sessions.length===0?<div className="p-8 text-center text-sm text-[#737782]">No active sessions found.</div>:<div className="divide-y">{sessions.map(s=>{const Icon=iconFor(s.device?.platform); return <div key={s.id} className="flex flex-col gap-4 p-4 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><div className="rounded-lg bg-[#eff4ff] p-2 text-[#004287]"><Icon size={20}/></div><div><div className="font-semibold">{label(s.device?.friendly_name||s.device?.device_name||s.user_agent||"Device")}{s.is_current&&<span className="ml-2 rounded-full bg-[#e7f5ed] px-2 py-0.5 text-[10px] font-bold text-[#006d40]">CURRENT</span>}</div><div className="text-xs text-[#737782]">{s.device?.platform||"web"} · {s.ip_address||"IP unavailable"}</div></div></div><div className="text-sm text-[#424751]">{s.last_activity_at?new Date(s.last_activity_at).toLocaleString("en-IN"):s.created_at?new Date(s.created_at).toLocaleString("en-IN"):"—"}</div>{!s.is_current&&<button onClick={()=>revoke(s.id)} className="inline-flex items-center gap-2 self-start rounded-lg px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50"><LogOut size={16}/> Revoke</button>}</div>})}</div>}</div><button onClick={()=>navigate("/profile")} className="mt-5 text-sm font-semibold text-[#004287]">Back to profile</button></main><AuthFooter/></div>;
}
