"""add customer model

Revision ID: 44a9b3366d53
Revises: 9202c826aabb
Create Date: 2026-08-22 14:13:17.421732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a9b3366d53'
down_revision: Union[str, Sequence[str], None] = '9202c826aabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_name'), 'customers', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customers_mobile_number'), 'customers', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_customers_pharmacy_id'), 'customers', ['pharmacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_pharmacy_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
