"""add pharmacy settings model

Revision ID: 7cf89e6c3d56
Revises: f28c11e4fd66
Create Date: 2026-08-22 14:29:06.066165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf89e6c3d56'
down_revision: Union[str, Sequence[str], None] = 'f28c11e4fd66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacy_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('default_gst_percentage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('invoice_template', sa.String(), nullable=False),
    sa.Column('printer_settings', sa.String(), nullable=False),
    sa.Column('barcode_settings', sa.String(), nullable=False),
    sa.Column('backup_settings', sa.String(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('audit_log_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_settings_pharmacy_id'), 'pharmacy_settings', ['pharmacy_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacy_settings_pharmacy_id'), table_name='pharmacy_settings')
    op.drop_table('pharmacy_settings')
    # ### end Alembic commands ###
