"""add supplier and purchase models

Revision ID: 8affa269ca3e
Revises: a332bcebc555
Create Date: 2026-08-22 14:05:40.330356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8affa269ca3e'
down_revision: Union[str, Sequence[str], None] = 'a332bcebc555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_gstin'), 'suppliers', ['gstin'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_pharmacy_id'), 'suppliers', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_suppliers_phone'), 'suppliers', ['phone'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('approved_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoices_branch_id'), 'purchase_invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_invoice_number'), 'purchase_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_pharmacy_id'), 'purchase_invoices', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_supplier_id'), 'purchase_invoices', ['supplier_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('purchase_id', sa.String(), nullable=False),
    sa.Column('medicine_id', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('free_quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_medicine_id'), 'purchase_items', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_medicine_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_purchase_invoices_supplier_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_pharmacy_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_invoice_number'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_branch_id'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_suppliers_phone'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_pharmacy_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_gstin'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
