"""add inventory ledger model

Revision ID: 9202c826aabb
Revises: 8affa269ca3e
Create Date: 2026-08-22 14:11:11.298725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9202c826aabb'
down_revision: Union[str, Sequence[str], None] = '8affa269ca3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('medicine_id', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_ledger_batch_number'), 'inventory_ledger', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_branch_id'), 'inventory_ledger', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_medicine_id'), 'inventory_ledger', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_pharmacy_id'), 'inventory_ledger', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_reference_id'), 'inventory_ledger', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_transaction_type'), 'inventory_ledger', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_ledger_transaction_type'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_reference_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_pharmacy_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_medicine_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_branch_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_batch_number'), table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    # ### end Alembic commands ###
