"""add medicine and batch

Revision ID: a332bcebc555
Revises: 
Create Date: 2026-08-22 14:00:18.048267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a332bcebc555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_identifier', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('friendly_name', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('push_token', sa.Text(), nullable=True),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_identifier', name='uq_user_device_identifier')
    )
    op.create_index('ix_devices_user_id_is_active', 'devices', ['user_id', 'is_active'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('pharmacies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('drug_license_document_id', sa.String(), nullable=True),
    sa.Column('gst_certificate_document_id', sa.String(), nullable=True),
    sa.Column('pan_document_id', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_ifsc', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_gst_number'), 'pharmacies', ['gst_number'], unique=True)
    op.create_index(op.f('ix_pharmacies_owner_user_id'), 'pharmacies', ['owner_user_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('settings_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_pharmacy_id'), 'branches', ['pharmacy_id'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('schedule_type', sa.String(), nullable=True),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('gst_percentage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_stock_level', sa.Integer(), nullable=True),
    sa.Column('rack', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_barcode'), 'medicines', ['barcode'], unique=True)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_index(op.f('ix_medicines_pharmacy_id'), 'medicines', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_medicines_sku'), 'medicines', ['sku'], unique=True)
    op.create_table('pharmacy_owners',
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pharmacy_id', 'user_id')
    )
    op.create_index(op.f('ix_pharmacy_owners_user_id'), 'pharmacy_owners', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_reason', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_device_id_revoked', 'sessions', ['device_id', 'revoked'], unique=False)
    op.create_index('ix_sessions_expires_at_revoked', 'sessions', ['expires_at', 'revoked'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index('ix_sessions_user_id_revoked', 'sessions', ['user_id', 'revoked'], unique=False)
    op.create_table('staff_roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_roles_pharmacy_id'), 'staff_roles', ['pharmacy_id'], unique=False)
    op.create_index('uq_pharmacy_role_name', 'staff_roles', ['pharmacy_id', 'name'], unique=True, postgresql_where=sa.text('pharmacy_id IS NOT NULL'))
    op.create_index('uq_system_role_name', 'staff_roles', ['name'], unique=True, postgresql_where=sa.text('pharmacy_id IS NULL'))
    op.create_table('login_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_history_user_id_created_at', 'login_history', ['user_id', 'created_at'], unique=False)
    op.create_table('medicine_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('medicine_id', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_batches_batch_number'), 'medicine_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_medicine_batches_medicine_id'), 'medicine_batches', ['medicine_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['staff_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('staff_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('employee_code', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['staff_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_members_branch_id'), 'staff_members', ['branch_id'], unique=False)
    op.create_index(op.f('ix_staff_members_contact_email'), 'staff_members', ['contact_email'], unique=False)
    op.create_index(op.f('ix_staff_members_contact_phone'), 'staff_members', ['contact_phone'], unique=False)
    op.create_index(op.f('ix_staff_members_pharmacy_id'), 'staff_members', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_staff_members_role_id'), 'staff_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_staff_members_user_id'), 'staff_members', ['user_id'], unique=False)
    op.create_index('ix_staff_pharmacy_branch_status', 'staff_members', ['pharmacy_id', 'branch_id', 'status'], unique=False)
    op.create_index('uq_staff_pharmacy_email', 'staff_members', ['pharmacy_id', 'contact_email'], unique=True, postgresql_where=sa.text('contact_email IS NOT NULL'))
    op.create_index('uq_staff_pharmacy_phone', 'staff_members', ['pharmacy_id', 'contact_phone'], unique=True, postgresql_where=sa.text('contact_phone IS NOT NULL'))
    op.create_index('uq_staff_pharmacy_user', 'staff_members', ['pharmacy_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('attendance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('staff_id', sa.String(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('working_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_pharmacy_branch_dates', 'attendance_records', ['pharmacy_id', 'branch_id', 'check_in_at'], unique=False)
    op.create_index(op.f('ix_attendance_records_branch_id'), 'attendance_records', ['branch_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_pharmacy_id'), 'attendance_records', ['pharmacy_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_staff_id'), 'attendance_records', ['staff_id'], unique=False)
    op.create_index('uq_staff_active_checkin', 'attendance_records', ['staff_id'], unique=True, postgresql_where=sa.text('check_out_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_staff_active_checkin', table_name='attendance_records', postgresql_where=sa.text('check_out_at IS NULL'))
    op.drop_index(op.f('ix_attendance_records_staff_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_pharmacy_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_branch_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_pharmacy_branch_dates', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('uq_staff_pharmacy_user', table_name='staff_members', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('uq_staff_pharmacy_phone', table_name='staff_members', postgresql_where=sa.text('contact_phone IS NOT NULL'))
    op.drop_index('uq_staff_pharmacy_email', table_name='staff_members', postgresql_where=sa.text('contact_email IS NOT NULL'))
    op.drop_index('ix_staff_pharmacy_branch_status', table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_user_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_role_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_pharmacy_id'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_contact_phone'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_contact_email'), table_name='staff_members')
    op.drop_index(op.f('ix_staff_members_branch_id'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_medicine_batches_medicine_id'), table_name='medicine_batches')
    op.drop_index(op.f('ix_medicine_batches_batch_number'), table_name='medicine_batches')
    op.drop_table('medicine_batches')
    op.drop_index('ix_login_history_user_id_created_at', table_name='login_history')
    op.drop_table('login_history')
    op.drop_index('uq_system_role_name', table_name='staff_roles', postgresql_where=sa.text('pharmacy_id IS NULL'))
    op.drop_index('uq_pharmacy_role_name', table_name='staff_roles', postgresql_where=sa.text('pharmacy_id IS NOT NULL'))
    op.drop_index(op.f('ix_staff_roles_pharmacy_id'), table_name='staff_roles')
    op.drop_table('staff_roles')
    op.drop_index('ix_sessions_user_id_revoked', table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index('ix_sessions_expires_at_revoked', table_name='sessions')
    op.drop_index('ix_sessions_device_id_revoked', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_pharmacy_owners_user_id'), table_name='pharmacy_owners')
    op.drop_table('pharmacy_owners')
    op.drop_index(op.f('ix_medicines_sku'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_pharmacy_id'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_barcode'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_branches_pharmacy_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_pharmacies_owner_user_id'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_gst_number'), table_name='pharmacies')
    op.drop_table('pharmacies')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index('ix_devices_user_id_is_active', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
