"""add billing and sales models

Revision ID: dc13139931e8
Revises: 44a9b3366d53
Create Date: 2026-08-22 14:17:55.681869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc13139931e8'
down_revision: Union[str, Sequence[str], None] = '44a9b3366d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hold_bills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('hold_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('items_json', sa.Text(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hold_bills_branch_id'), 'hold_bills', ['branch_id'], unique=False)
    op.create_index(op.f('ix_hold_bills_hold_number'), 'hold_bills', ['hold_number'], unique=True)
    op.create_index(op.f('ix_hold_bills_pharmacy_id'), 'hold_bills', ['pharmacy_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upi_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wallet_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_branch_id'), 'invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_pharmacy_id'), 'invoices', ['pharmacy_id'], unique=False)
    op.create_table('exchange_bills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('old_medicine_id', sa.String(), nullable=False),
    sa.Column('old_medicine_name', sa.String(length=255), nullable=False),
    sa.Column('old_batch_number', sa.String(length=100), nullable=False),
    sa.Column('old_quantity', sa.Integer(), nullable=False),
    sa.Column('new_medicine_id', sa.String(), nullable=False),
    sa.Column('new_medicine_name', sa.String(length=255), nullable=False),
    sa.Column('new_batch_number', sa.String(length=100), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('price_difference', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['new_medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['old_medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_bills_branch_id'), 'exchange_bills', ['branch_id'], unique=False)
    op.create_index(op.f('ix_exchange_bills_invoice_id'), 'exchange_bills', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_exchange_bills_invoice_number'), 'exchange_bills', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_exchange_bills_pharmacy_id'), 'exchange_bills', ['pharmacy_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('medicine_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_percentage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_batch_id'), 'invoice_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_medicine_id'), 'invoice_items', ['medicine_id'], unique=False)
    op.create_table('return_bills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('medicine_id', sa.String(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_bills_branch_id'), 'return_bills', ['branch_id'], unique=False)
    op.create_index(op.f('ix_return_bills_invoice_id'), 'return_bills', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_return_bills_invoice_number'), 'return_bills', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_return_bills_pharmacy_id'), 'return_bills', ['pharmacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_bills_pharmacy_id'), table_name='return_bills')
    op.drop_index(op.f('ix_return_bills_invoice_number'), table_name='return_bills')
    op.drop_index(op.f('ix_return_bills_invoice_id'), table_name='return_bills')
    op.drop_index(op.f('ix_return_bills_branch_id'), table_name='return_bills')
    op.drop_table('return_bills')
    op.drop_index(op.f('ix_invoice_items_medicine_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_batch_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_exchange_bills_pharmacy_id'), table_name='exchange_bills')
    op.drop_index(op.f('ix_exchange_bills_invoice_number'), table_name='exchange_bills')
    op.drop_index(op.f('ix_exchange_bills_invoice_id'), table_name='exchange_bills')
    op.drop_index(op.f('ix_exchange_bills_branch_id'), table_name='exchange_bills')
    op.drop_table('exchange_bills')
    op.drop_index(op.f('ix_invoices_pharmacy_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_branch_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_hold_bills_pharmacy_id'), table_name='hold_bills')
    op.drop_index(op.f('ix_hold_bills_hold_number'), table_name='hold_bills')
    op.drop_index(op.f('ix_hold_bills_branch_id'), table_name='hold_bills')
    op.drop_table('hold_bills')
    # ### end Alembic commands ###
